#!/usr/bin/env python3
"""post_llm_call hook: fast AI-tell check only.

Runs in <5ms. Regex-only, no network, no subprocess.
Writes to cache so pre_llm_call can inject on next turn.
"""

import json
import os
import re
import sys
import time
from pathlib import Path

HERMES_HOME = Path(os.path.expanduser("~/.hermes"))
CACHE_DIR = HERMES_HOME / "cache" / "self-qa"
CACHE_FILE = CACHE_DIR / "last-qa-check.json"

# AI-tell patterns (unicode literals)
AI_TELL_PATTERNS = [
    ("\u2014", "em dash (U+2014)"),
    ("\u2013", "en dash (U+2013)"),
    ("\u201c\u201d", "curly double quotes"),
    ("\u2018\u2019", "curly single quotes"),
    ("\u2019", "right single quote / apostrophe replacement"),
    ("\u2026", "unicode ellipsis"),
]

AI_TELL_PHRASES = [
    "as an AI",
    "as a large language model",
    "as an AI language model",
    "as an AI assistant",
    "auto-generated by AI",
    "AUTO-GENERATED",
    "I am a large language model",
    "I'm a large language model",
]


def main():
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return
        payload = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return

    assistant_response = payload.get("assistant_response", "") or payload.get(
        "response", ""
    )

    if len(assistant_response) < 100:
        return

    issues = []

    for pattern, label in AI_TELL_PATTERNS:
        if pattern in assistant_response:
            issues.append(f"Non-ASCII: {label}")

    for phrase in AI_TELL_PHRASES:
        if phrase.lower() in assistant_response.lower():
            issues.append(f"Phrase: '{phrase}'")

    code_blocks = re.findall(r"```(?:\w*)\n([\s\S]*?)```", assistant_response)
    for block in code_blocks:
        for line in block.split("\n"):
            stripped = line.lstrip("#/ ")
            for word in (
                "AI",
                "AI-generated",
                "auto-generated",
                "Claude",
                "GPT",
                "LLM",
            ):
                if word in stripped and (
                    "generated" in stripped.lower() or "written" in stripped.lower()
                ):
                    issues.append(
                        f"Code comment references AI: '{stripped.strip()[:80]}'"
                    )
                    break

    if issues:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        with open(CACHE_FILE, "w") as f:
            json.dump(
                {
                    "timestamp": time.time(),
                    "issues": issues,
                    "source": "fast_check",
                },
                f,
            )


if __name__ == "__main__":
    main()
